import Navbar from "@/components/nav/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import SideBar from "@/components/sidebar/sidebar";
import Suggestions from "@/components/content_suggestions/suggestions";
import GlobalContext from "@/context/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Youtube Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContext>
          <Navbar />
          <main className="flex">{children}</main>
        </GlobalContext>
      </body>
    </html>
  );
}
