import Navbar from "@/components/nav/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import SideBar from "@/components/sidebar/sidebar";
import Suggestions from "@/components/suggestions";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="flex">
          <SideBar />
          <section
            className=" pt-[50px] lg:w-[calc(100vw-267px)] md:w-[calc(100vw-120px)] w-full lg:ml-[250px]
         md:ml-[100px] relative"
          >
            <Suggestions />
            
            <section className='w-full pt-[12vh]'>
            {children}
            </section>
          </section>
        </main>
      </body>
    </html>
  );
}
